### ISSUE TITLE
[Firefox] UI bug with sroll overflow [v2.3.2]

### ISSUE THREAD

**Issue by pmioduszewski** [kawamataryo/chikamichi#13]
**OS:** macOS Monterey 12.2 M1
**Browser:** Firefox 96.0.3

Sometimes search results making chikamichi window overflow like on screen below. X and Y axis.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/43101981/151671728-1fc0afc9-796f-499b-9dc8-60fc56dd8f1e.png">

**Comment by kawamataryo** [comment]
Oh..
Thanks for the issue!
I'll fix it in the next release.

**Comment by kawamataryo** [comment]
@pmioduszewski 

Hi, I have released version 2.5.0 of chikamichi, which fixes the overflow bug. Please check here to see if it is fixed.

**Comment by pmioduszewski** [comment]
thx! working fine now :)
