### ISSUE TITLE
Unfortunately, Ctrl+Enter doesn't work on Vivaldi.

### ISSUE THREAD

**Issue by shift-e** [kawamataryo/chikamichi#14]
Thank you for your excellent extension.
Could you fix it?

**Comment by kawamataryo** [comment]
Hmmm.
It works in my environment.

- Mac OS Montery version 12.0.1
- Vivaldi | 5.0.2497.48 (Stable channel) (arm64)
- Chikamichi v2.5.0

https://user-images.githubusercontent.com/11070996/151697676-15e20cb6-3b31-4524-98b6-d7f4591a4ab5.mp4

Can you give me some information for reproduction?

**Comment by shift-e** [comment]
Thank you for your reply.
Is it better to write in Japanese?

環境は以下です。
Chikamichi: 2.5.0
OS: windows10 21H1
Vivaldi: 5.0.2497.48 (Stable channel) (64-bit)

Ctrl+Enterは、クリーン・プロファイルのVivaldiでセキュリティ・ソフトを閉じても、動きませんでした。（Enter、Ctrl+p、Ctrl+n は問題なく動きます）
試してみましたが、Edgeでも同じ状況です。

**Comment by kawamataryo** [comment]
なるほど。ありがとうございます。
WindownsのChromeで動作確認したところ、再現できました。

Windowsだとctrl + enterのキーイベントを上手くハンドリングできないようです。
原因調査しますね

**Comment by kawamataryo** [comment]
@shift-e 

ver 2.5.1 で修正しました。
Chikamichiを最新にアップデート後、動作確認お願いします。

**Comment by shift-e** [comment]
嗚呼・・・完璧に動作します！ 山が崩れて海が干上がるくらいに感激です！
この度は１ユーザーの我儘への神対応を有難うござまいました。
