### ISSUE TITLE
Slow writing

### ISSUE THREAD

**Issue by gitlover4ever** [kawamataryo/chikamichi#151]
I understand the extension need search-time, especially when there are a lot of tabs. However, instead of just waiting to show me the results, the extension slows down the input bar, and so each character appears slowly.

I have a powerful desktop computer.
Browser Firefox 99.0 on Windows 10
Extension version: 2.14.2

**Comment by kawamataryo** [comment]
Thanks for the issue!

I am working on performance improvements right now.
Please wait a little longer.
