### ISSUE TITLE
Cannot distinguish page titles with a common prefix

### ISSUE THREAD

**Issue by yigarashi-9** [kawamataryo/chikamichi#20]
Hi!
I like the concept very much, but I have a problem in use.

## Problem
Page titles can have a common prefix, such as, its service name, a user name, a project name, etc. I cannot distinguish such pages as follows in many cases...

- long long project name | a `https...`
- long long project name | b `https...`
- ...

I hope I can see much longer titles like the address bar!

## Possible solutions
- ~~Make the popup wider~~
- ~~Make width of the popup configurable~~
  - I apologize that I don't know the limit of the popup size. You have already maximized it :bow:
- Make titles longer and make urls shorter
- ...

**Comment by kawamataryo** [comment]
Thank you for the Issue.
I'll look into fixing it.

**Comment by kawamataryo** [comment]
@yigarashi-9 

Hi. Fixed it with #21

**Comment by yigarashi-9** [comment]
Thank you very much for your fast and clever solution!!
I'm looking forward to using it 😄
