### ISSUE TITLE
Does it support searching with bookmark's parent folder name?

### ISSUE THREAD

**Issue by zzeitt** [kawamataryo/chikamichi#22]
Feature request for this convenient extension.

**Comment by kawamataryo** [comment]
Hi, thanks for the feature request.
I will consider adding the feature.

**Comment by zzeitt** [comment]
Sorry for my late reaction. The feature is so cool (๑•̀ㅂ•́)و✧

However, it would be better if this extension support searching among **all (parents) folders**.
> For example, given the structure of bookmarks as `"test/folder1/folder2/test-item"`,
> when the input is `"folder1"`,
> the output should be <kbd>test/**folder1**/folder2/test-item</kbd>.

Here I compared the fuzzy searching of this extension and the Edge browser's built-in function.
The extension failed to locate the `"folder1"`.

![tmp drawio](https://user-images.githubusercontent.com/30381410/155089126-986150b8-c360-41ea-a2cb-d7cd5780f053.png)

**Comment by kawamataryo** [comment]
@zzeitt 

Thanks for the reply!

I see. I'll try to expand the function so that you can search there as well :)
Please wait a while.

**Comment by kawamataryo** [comment]
@zzeitt 

Hi. I fixed it.
All parent folder names are now searchable.

https://user-images.githubusercontent.com/11070996/155625048-7d7dc03d-9fda-42d5-a93b-74b131c15b42.mp4

Please check.

**Comment by zzeitt** [comment]
> @zzeitt 
> 
> 
> 
> Hi. I fixed it.
> 
> In v2.13.2,  All parent folder names are now searchable.
> 
> 
> 
> https://user-images.githubusercontent.com/11070996/155625048-7d7dc03d-9fda-42d5-a93b-74b131c15b42.mp4
> 
> 
> 
> Please check.
> 
> 

Wow that's awesome. I will test it the moment I reach my computer.

**Comment by zzeitt** [comment]
Hi @kawamataryo, it works now! Thank you for listening to my voice.

By the way, do you have any plan about publishing *chikamichi* on [Edge Webstore](https://microsoftedge.microsoft.com/addons/)? Because I have to reinstall the extension everytime I want a update on Edge browser.

**Comment by kawamataryo** [comment]
@zzeitt 

Thanks! That's good.
I'll also try to publish to the Edge Webstore.

**Comment by kawamataryo** [comment]
@zzeitt 

Hi. I published Edge web store.
You can install here.

https://microsoftedge.microsoft.com/addons/detail/chikamichi-quickly-find/kgbibnihcjkbcjbngneigamkphnoipli
