### ISSUE TITLE
11件以上の検索結果について

### ISSUE THREAD

**Issue by KentaroJay** [kawamataryo/chikamichi#25]
はじめまして、高橋と申します。

chikamichi、大変便利に使わさせていただいております！
11件目以降の検索結果が表示されないのは仕様でしょうか？また今後11件目以降を表示するように変更する予定はありますでしょうか？

**Comment by kawamataryo** [comment]
ご使用ありがとうございます！

11件目以降が表示されないのは現在の仕様です 🙇‍♂️
11件目以降も表示するように改修は検討しています！

**Comment by kawamataryo** [comment]
@KentaroJay 

こちらで対応してみました！パフォーマンスの兼ね合いもあり、最大100件表示するようにしています

https://github.com/kawamataryo/chikamichi/pull/26

**Comment by kawamataryo** [comment]
v2.9.0で使えるようになる予定です！

**Comment by KentaroJay** [comment]
@kawamataryo さん、ご対応ありがとうございます！
おおー！いい感じですね🙇‍♂️
