### ISSUE TITLE
Shortcut doesn't work on Mac

### ISSUE THREAD

**Issue by KentaroJay** [kawamataryo/chikamichi#438]
Macでalt(option) + kを入力してもchikamichiが立ち上がりません。

**Comment by kawamataryo** [comment]
@KentaroJay 

Issueありがとうございます！
Manifest v3に上げた関係で、少しバグがるようで今修正リリース作成中です。

ワークアラウンドですが、Chrome Extensionのショートカット設定に表示されている入力欄の下の方に、設定したいショートカットキーを入れれば動くようになります。

<img width="1442" alt="Screen Shot 2022-07-30 at 13 05 09" src="https://user-images.githubusercontent.com/11070996/181871731-f607a744-e090-43ef-8502-426e4b0be38a.png">

**Comment by KentaroJay** [comment]
ご対応ありがとうございます🙇‍♂️

**Comment by kawamataryo** [comment]
v3.0.1で修正されたのでクローズします
