### ISSUE TITLE
Sorting History and searches by most recent?

### ISSUE THREAD

**Issue by gitlover4ever** [kawamataryo/chikamichi#544]
Love the extension, however I find it hard to find something in history, where I can only remember one word because it isn't sorted after access time.

Would be nice if you could sort it like that, and even better if you could add access time besides each entry. Otherwise, I prefer the inbuilt history browser.

**Comment by kawamataryo** [comment]
Thank you for the issue!
I too think sorting by access time would be useful.

Not right now, but I am trying to add it.
Please wait for a while.

**Comment by kawamataryo** [comment]
@gitlover4ever 

こちらで対応しました！
Storeの審査があるので、2〜3日中にリリースします
#639

**Comment by kawamataryo** [comment]
@gitlover4ever 

Fix it #649.
Please wait until v3.2.1 is released.
