### ISSUE TITLE
Open in a new tab as a default

### ISSUE THREAD

**Issue by MeF0504** [kawamataryo/chikamichi#582]
現在は
- Enterだと今のタブで開く
- ctrl+Enterだと新規タブで開く

という動作ですが，設定でこの設定をswapできるようにして欲しいです。

期待する動作
- 設定項目：Open page in new ta as a default
  - off: Enterで現在のタブで開く，ctrl+Enter で新規タブで開く
  - on: Enterで新規タブで開く，ctrl+Enter で現在のタブで開く

**Comment by kawamataryo** [comment]
なるほど。あると便利かもですね。
直近業務が忙しいので少し時間がかかりそうですが、対応しようと思います

**Comment by kawamataryo** [comment]
@gitlover4ever 

こちらで対応しました！
Storeの審査があるので、2〜3日中にリリースします
#639
