### ISSUE TITLE
"Access your data for all websites" permission needed?

### ISSUE THREAD

**Issue by Gitoffthelawn** [kawamataryo/chikamichi#6]
Thank you for this extension.

Is the "Access your data for all websites" really needed?  If so, why?

**Comment by kawamataryo** [comment]
Thanks for the question!
This setting is the permissions required for the chikamichi's modal to open on all web sites.
If this is not specified, the modal will not open, as it will block the loading of content_script.js.

The actual description in manifest.json corresponds to this.
https://github.com/kawamataryo/chikamichi/blob/main/src/manifest.ts#L39-L50

For a more detailed explanation, please refer to the following site

https://support.mozilla.org/en-US/questions/1299613

**Comment by Gitoffthelawn** [comment]
You're welcome and thank you for the answer.

Makes sense.

Thinking aloud here...

Would it be possible/reasonable to use a toolbar popup instead of an overlay modal injected into the DOM?  (I haven't reviewed the code yet, but I'm guessing that's what you are doing.)

I'm trying to brainstorm a way to have almost the same functionality without needing that big permission.

**Comment by kawamataryo** [comment]
> Would it be possible/reasonable to use a toolbar popup instead of an overlay modal injected into the DOM? (I haven't reviewed the code yet, but I'm guessing that's what you are doing.)

I think it is possible to show history and bookmark information in popup.
However, I don't know if it is possible to ensure the same operability as now. I chose to use dialogs because I wanted to be able to control everything with keyboard shortcuts.

**Comment by Gitoffthelawn** [comment]
Hmmm... still thinking aloud...

What about displaying content in the sidebar?  I think that allows keyboard shortcuts.

**Comment by kawamataryo** [comment]
Ah.
I didn't image the popup well.
When you say "display in popup", are you thinking of something like black-menu?

https://apps.jeurissen.co/black-menu-for-google 

I think it's worth a try.

**Comment by kawamataryo** [comment]
I'll consider fix it so that it shows up in a popup.

**Comment by Gitoffthelawn** [comment]
> Ah. I didn't image the popup well. When you say "display in popup", are you thinking of something like black-menu?
> 
> https://apps.jeurissen.co/black-menu-for-google
> 
> I think it's worth a try.

I have to experiment with that extension to see if that's similar to what I meant.  Either way, my primary interest is in having the most functionality (and keeping the UX excellent) without needing the "Access your data for all websites" permission.

Also, DOM injections can get messy, cause issues, and be hard to maintain, so when possible, I think it's best to avoid that technique.  That said, sometimes it is the only way to get the desired functionality.

**Comment by kawamataryo** [comment]
@Gitoffthelawn 
Hi 👋
I made a new version.
In this version, the DOM is not injected from content script, and the form is displayed in a popup.

https://github.com/kawamataryo/chikamichi/pull/9

The release to the store is still some way off, but I think this version will resolve this issue.

**Comment by Gitoffthelawn** [comment]
Wow, that's exciting!  ありがとう！
